---
- name: CA SETUP |  OS type
  fail:
    msg: "Sorry, your OS type is not supported"
  when: ansible_distribution != "Ubuntu"

- name: CA SETUP |  Ensure CA dir
  file:
    path: "{{ item }}"
    mode: 0777
    owner: root
    group: root
    state: directory
  with_items:
    - "{{ ca_dir }}/certs/"
    - "{{ ca_dir }}/crl/"
    - "{{ ca_dir }}/csr/"
    - "{{ ca_dir }}/private/"
