---
- name: Check OS type
  fail:
    msg: "Sorry, your OS type is not supported"
  when: ansible_distribution != "Ubuntu"

- name: Ensure CA dir
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0750
    state: directory
  with_items:
    - "{{ certs_dir }}"
    - "{{ crl_dir }}"
    - "{{ csr_dir }}"
    - "{{ keys_dir }}"
