---
- name: Copy to openssl config
  template:
    src: openssl.cnf
    dest: "{{ ca_dir }}/openssl.cnf"
    mode: 0644
    owner: root
    group: root

- name: Create serial
  shell: echo "01" > serial
  args:
    chdir: "{{ ca_dir }}"
    creates: serial

- name: Create index.txt
  file:
    path: "{{ ca_dir }}/index.txt"
    state: touch
    mode: 0644
    owner: root
    group: root
  changed_when: false

- name: Create crlnumber
  shell: echo 01 > {{ crl_dir }}/crlnumber
  args:
    creates: "{{ crl_dir }}/crlnumber"
