---
- name: CA SETUP |  Install latest version of OpenSSL
  package:
    name: openssl
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: CA SETUP |  Install latest version of syslog-ng
  package:
    name: syslog-ng
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: CA SETUP |  Ensure dirs
  file:
    state: directory
    owner: root
    group: root
    path: "{{ item }}"
  with_items:
    - "{{ ca_dir }}/private" 
    - "{{ ca_dir }}/csr"
    - "{{ ca_dir }}/certs"
