---
- name: Converge
  hosts: all

  vars:
    ca_dir: /opt/syslog_ca
    fetch_ca_cert: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false
      when: ansible_os_family == 'Debian'

  roles:
    - role: ca
